"""Lesson 18.2 / s3: A Modelfile from the tokenizer

Summary and purpose:
Do it

HTML instruction: bash — run in the operator shell, in the kit (downloads the tokenizer's files, about 31 MB; no GPU, no Google Cloud)
Category: required. Read the matching README checkpoint before Run.
Prerequisites: demo_03_01_do_it
Expected observation: [transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
# GENERATED by make_modelfile.py from the tokenizer. Do not hand-edit.
# Regenerate whenever the checkpoint changes - the template belongs to the
# weights, not to the project.

FROM ./documind-slm.gguf

TEMPLATE \"\"\"<bos><|turn>user
{{ .Prompt }}<turn|>
<|turn>model
\"\"\"

PARAMETER stop "<turn|>"

PARAMETER num_ctx 4096

Evidence: the active lesson session records this attempt and command output.
A completed process is not proof that every sample value matches your lane.
Source: https://github.com/netsetos/agents_workshop/blob/main/lessons/18-serving/18.2-ollama-slm/Netsetos_GCP_Capstone_18.2_Ollama_SLM_WIX.html#L438

"""
from workshop_helpers.session import DemoSession

# Change only for a deliberate replay after inspecting this step's effects.
REPEAT = False

# The lesson's actual kit commands, visible here in the same order.
COMMANDS = """cd services/slm && HF_HUB_DISABLE_PROGRESS_BARS=1 ~/tf-venv/bin/python make_modelfile.py --model unsloth/gemma-4-E2B-it --gguf documind-slm.gguf > ~/Modelfile.182
cd ../.. && cat ~/Modelfile.182
"""


def demonstrate(session):
    """Run Do it at this checkpoint.

    Do it

    Args: session is the active lesson run, with validated settings and saved prerequisites.
    Operations: bash — run in the operator shell, in the kit (downloads the tokenizer's files, about 31 MB; no GPU, no Google Cloud).
    Returns: None; observations are printed or saved by the lesson code.
    Failures propagate to the session; inspect its failed attempt before continuing.
    """
    # Preserve the kit CLI's arguments, conditions and observation order.
    session.shell(COMMANDS)


def main():
    """Resume this lesson and execute only this checkpoint in the IDE interpreter."""
    with DemoSession(__file__, live=False, repeat=REPEAT) as session:
        demonstrate(session)


if __name__ == "__main__":
    main()
